# Generated by Django 2.1.5 on 2019-01-09 07:23

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Archive",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField(unique=True)),
                (
                    "display_in_menu",
                    models.BooleanField(
                        help_text='Set this to display in the archive menu. Otherwise found under "Read more"'
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        help_text="Set this to publish the entire archive"
                    ),
                ),
                ("keywords", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(
                        help_text="Short description of the archive, 200 symbols.",
                        max_length=200,
                    ),
                ),
                (
                    "thumbnail_image",
                    models.ImageField(
                        help_text="To crop the image, simply click save and continue.",
                        upload_to="archive/archive/",
                    ),
                ),
                (
                    "thumbnail_image_crop",
                    image_cropping.fields.ImageRatioField(
                        "thumbnail_image",
                        "600x600",
                        adapt_rotation=False,
                        allow_fullsize=False,
                        free_crop=False,
                        help_text=None,
                        hide_image_field=False,
                        size_warning=True,
                        verbose_name="thumbnail image crop",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alt", models.CharField(max_length=50)),
                (
                    "description",
                    models.TextField(
                        help_text="Short description of the image, 200 symbols.",
                        max_length=200,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="To crop the image, simply click save and continue.",
                        upload_to="archive/images/",
                    ),
                ),
                (
                    "image_crop",
                    image_cropping.fields.ImageRatioField(
                        "image",
                        "600x600",
                        adapt_rotation=False,
                        allow_fullsize=False,
                        free_crop=False,
                        help_text=None,
                        hide_image_field=False,
                        size_warning=True,
                        verbose_name="image crop",
                    ),
                ),
                (
                    "archive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="archive.Archive",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alt", models.CharField(max_length=50)),
                (
                    "description",
                    models.TextField(
                        help_text="Short description of the video, 200 symbols.",
                        max_length=200,
                    ),
                ),
                ("link", embed_video.fields.EmbedVideoField()),
                (
                    "archive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="archive.Archive",
                    ),
                ),
            ],
        ),
    ]
