"""
Django settings for nablarevyen project.

Generated by 'django-admin startproject' using Django 2.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")

# Variable content
VARIABLE_CONTENT = os.environ.get("VARIABLE_CONTENT", os.path.join(BASE_DIR, "var"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ai7z9^b14!l8z^4r9x+v#=$cgv=2hqx1n9w^_^wkne+n7(5(@p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

APPEND_SLASH = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

X_FRAME_OPTIONS = 'SAMEORIGIN'

SECURE_CONTENT_TYPE_NOSNIFF = True

SECURE_BROWSER_XSS_FILTER = True


# Application definition

INSTALLED_APPS = [
    # External apps
    'ckeditor',
    'ckeditor_uploader',
    'sorl.thumbnail',
    'django_instagram',
    'easy_thumbnails',
    'image_cropping',
    'embed_video',
    # Internal apps
    'apps.frontpage',
    'apps.articles',
    'apps.about',
    'apps.groups',
    'apps.archive',
    'apps.applications',
    # Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'nablarevyen.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'shared/templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nablarevyen.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'var/db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'nb'

TIME_ZONE = 'Europe/Oslo'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(VARIABLE_CONTENT, 'static_collected')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'shared/static'),
]


# Media files (MEDIA_ROOT is applied in the state settings file)
# https://docs.djangoproject.com/en/2.0/topics/files/

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(VARIABLE_CONTENT, 'media')


# django-ckeditor
# https://github.com/django-ckeditor/django-ckeditor#usage

CKEDITOR_UPLOAD_PATH = 'uploads/'

CKEDITOR_BROWSE_SHOW_DIRS = True

CKEDITOR_IMAGE_BACKEND = 'pillow'


# Email backend
# https://docs.djangoproject.com/en/2.0/topics/email/

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'dont-reply@localhost'


# django-image-cropping settings
# https://github.com/jonasundderwolf/django-image-cropping

from easy_thumbnails.conf import Settings as thumbnail_settings

THUMBNAIL_PROCESSORS = (
    'image_cropping.thumbnail_processors.crop_corners',
) + thumbnail_settings.THUMBNAIL_PROCESSORS

THUMBNAIL_HIGH_RESOLUTION = True
THUMBNAIL_QUALITY = 95

IMAGE_CROPPING_THUMB_SIZE = (200, 200)

IMAGE_CROPPING_SIZE_WARNING = True
