# Generated by Django 2.1.5 on 2019-01-09 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={
                "verbose_name": "Undergruppe",
                "verbose_name_plural": "Undergrupper",
            },
        ),
    ]
