# Generated by Django 2.1.4 on 2018-12-15 18:27

import ckeditor_uploader.fields
from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField()),
                ("title", models.CharField(max_length=50)),
                (
                    "image",
                    models.ImageField(
                        help_text="To crop the image, simply click save and continue.",
                        upload_to="uploads/%Y/",
                    ),
                ),
                (
                    "desktop_crop",
                    image_cropping.fields.ImageRatioField(
                        "image",
                        "700x300",
                        adapt_rotation=False,
                        allow_fullsize=False,
                        free_crop=False,
                        help_text=None,
                        hide_image_field=False,
                        size_warning=True,
                        verbose_name="desktop crop",
                    ),
                ),
                (
                    "mobile_crop",
                    image_cropping.fields.ImageRatioField(
                        "image",
                        "700x500",
                        adapt_rotation=False,
                        allow_fullsize=False,
                        free_crop=False,
                        help_text=None,
                        hide_image_field=False,
                        size_warning=True,
                        verbose_name="mobile crop",
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        help_text="Keywords used for search engine optimalization.",
                        max_length=60,
                    ),
                ),
                ("summary", models.TextField(max_length=150)),
                ("content", ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
