# Generated by Django 2.1.4 on 2018-12-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_auto_20181216_1325"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
