# Generated by Django 2.1.5 on 2019-01-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='phone',
            field=models.CharField(default=3, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='student_class',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
    ]
