# Generated by Django 2.1.5 on 2019-01-30 19:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_position_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='open',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
