# Generated by Django 2.1.5 on 2019-02-25 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_position_open"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Epostadresse"),
        ),
        migrations.AlterField(
            model_name="application",
            name="first_group",
            field=models.ForeignKey(
                blank=True,
                default="",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="applications_first",
                to="groups.Group",
                verbose_name="Førstevalg",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Navn"),
        ),
        migrations.AlterField(
            model_name="application",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="Telefonnummer"),
        ),
        migrations.AlterField(
            model_name="application",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="applications.Position",
                verbose_name="Opptak",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="second_group",
            field=models.ForeignKey(
                blank=True,
                default="",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="applications_second",
                to="groups.Group",
                verbose_name="Andrevalg",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="student_class",
            field=models.PositiveIntegerField(verbose_name="Klasse"),
        ),
        migrations.AlterField(
            model_name="application",
            name="text",
            field=models.TextField(verbose_name="Søknadstekst"),
        ),
        migrations.AlterField(
            model_name="application",
            name="third_group",
            field=models.ForeignKey(
                blank=True,
                default="",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="applications_third",
                to="groups.Group",
                verbose_name="Tredjevalg",
            ),
        ),
    ]
