# Generated by Django 2.1.5 on 2019-02-25 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0005_auto_20190225_1945"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="first_group",
            field=models.ForeignKey(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applications_first",
                to="groups.Group",
                verbose_name="Førstevalg",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="second_group",
            field=models.ForeignKey(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applications_second",
                to="groups.Group",
                verbose_name="Andrevalg",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="third_group",
            field=models.ForeignKey(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applications_third",
                to="groups.Group",
                verbose_name="Tredjevalg",
            ),
        ),
    ]
