# Generated by Django 2.1.5 on 2019-01-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontpage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="carouselitem",
            name="published",
            field=models.BooleanField(
                default=False, help_text="Set this to publish carousel item."
            ),
        ),
    ]
